<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

**Описание данных**
 - Признаки: пол, возраст и зарплата застрахованного, количество членов его семьи.
 - Целевой признак: количество страховых выплат клиенту за последние 5 лет.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('/datasets/insurance.csv')
df.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
df.duplicated().sum()

153

Имеются дубликаты, но с учетом данных таблицы, такое возможно, удалять их смысла нет

In [5]:
df.columns=['sex', 'age', 'salary', 'family', 'payments']

Преобразуем признаки и целевой признак в векторы:

In [6]:
X = df.drop('payments', axis=1).values
y = df.payments.values
X, y

(array([[1.00e+00, 4.10e+01, 4.96e+04, 1.00e+00],
        [0.00e+00, 4.60e+01, 3.80e+04, 1.00e+00],
        [0.00e+00, 2.90e+01, 2.10e+04, 0.00e+00],
        ...,
        [0.00e+00, 2.00e+01, 3.39e+04, 2.00e+00],
        [1.00e+00, 2.20e+01, 3.27e+04, 3.00e+00],
        [1.00e+00, 2.80e+01, 4.06e+04, 1.00e+00]]),
 array([0, 1, 0, ..., 0, 0, 0]))

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** При умножении признаков на обратимую матрицу качество линейной регрессии не изменится.

**Обоснование:**

Вместо $X - XP$

$$
a_{new} = XPw_{new}
$$
$$
w_{new} = ((XP)^TXP)^{-1}(XP)^Ty
$$

подставим w_{new} в a_{new} и преобразуем:

$$
a_{new} = XP((XP)^TXP)^{-1}(XP)^Ty = XP(P^TX^TXP)^{-1}P^TX^Ty = XP(X^TXP)^{-1}(P^T)^{-1}P^TX^Ty = XPP^{-1}(X^TX)^{-1}P^TX^Ty = XE(X^TX)^{-1}EX^Ty=X(X^TX)^{-1}X^Ty=Xw
$$

Примечания:
$$
(AB)^T=B^TA^T
$$

Таким образом:
$$
a_{new} = a
$$



Проверим изначальные значения линейной регрессии:

In [7]:
class Linear_r2: #Обучение линейной регрессии на признаках
    def __init__(self, features, target):
        self.model = LinearRegression()
        self.preds = self.model.fit(features, target).predict(features)
        self.score = r2_score(target, self.preds)

In [8]:
r2_initial = Linear_r2(X, y)
r2_initial.score

0.42494550286668

Отталкиевамся от значения R2 = 0.42

Создаем произвольную матрицу:

In [9]:
np.random.seed(125)
P = np.random.randint(100, size=(X.shape[1], X.shape[1]))
P

array([[61, 29, 98, 87],
       [67, 77, 86, 43],
       [59, 64, 37, 86],
       [98, 95, 27, 30]])

In [10]:
# Проверка обратимости матрицы P
P_inv = np.linalg.inv(P)
P_inv

array([[ 0.01946318, -0.02235339, -0.01668047,  0.02341399],
       [-0.02140401,  0.021283  ,  0.01448086, -0.00994578],
       [ 0.00345646,  0.0130447 , -0.00779438, -0.00637725],
       [ 0.00108884, -0.0061153 ,  0.01564843, -0.00591787]])

In [11]:
# Преобразование признаков  через матрицу P
X_transformed = X @ P
X_transformed.shape

(5000, 4)

In [12]:
X_transformed

array([[2929306., 3177681., 1838851., 4267480.],
       [2245180., 2435637., 1409983., 3270008.],
       [1240943., 1346233.,  779494., 1807247.],
       ...,
       [2001636., 2171330., 1256074., 2916320.],
       [1931129., 2094808., 1211971., 2813323.],
       [2397435., 2600680., 1504733., 3492921.]])

Обучим линейную регрессию и измерим её R2.

In [13]:
r2_transformed = Linear_r2(X_transformed, y)
r2_transformed.score

0.4249455028666701

**Вывод: Как мы видим, значительных изменений метрики R2 не произошло, что соответвует обоснованию выше**

## Алгоритм преобразования

In [14]:
features = df.drop('payments', axis=1)
target = df['payments']

Напишем алгоритм - функцию преобразования исходных данных в зашифрованный вид, закодировав исходную матрицу:

In [15]:
def encode(features):
    random_matrix = np.random.normal(0, 1, (features.shape[1], features.shape[1]))
    encoded_features = features.dot(random_matrix)
    return encoded_features

In [16]:
encode(features)

0             1             2             3
0    -21691.210848 -45845.997865 -52040.368065 -44175.332613
1    -16614.188114 -35152.312990 -39841.967091 -33839.570952
2     -9179.083914 -19432.278091 -22011.256807 -18700.572688
3    -18243.070361 -38519.504316 -43777.258141 -37139.669494
4    -11411.009548 -24136.321137 -27371.918049 -23245.428371
...            ...           ...           ...           ...
4995 -15615.819480 -32997.005057 -37459.194168 -31793.546537
4996 -22918.128322 -48415.599946 -54996.172176 -46669.291904
4997 -14830.720312 -31320.710234 -35583.024839 -30191.759414
4998 -14307.802180 -30219.386674 -34317.740367 -29123.193911
4999 -17757.491778 -37516.772881 -42608.061392 -36160.917431

[5000 rows x 4 columns]

Для расшифровки данных напишем алгоритм - функцию дешифрования, принимающая на вход зашифрованную матрицу encoded_features и возвращающая исходную features:

In [17]:
encoded_features = features.dot(P)

In [18]:
def decode(encoded_features):
    decoded_features = round(abs(encoded_features.dot(np.linalg.inv(P))))
    for i in decoded_features.iloc[:, [0, 3]]:
        decoded_features[i] = decoded_features[i].astype(int)
    decoded_features.columns = features.columns
    return decoded_features

In [19]:
decode(encoded_features)

sex   age   salary  family
0       1  41.0  49600.0       1
1       0  46.0  38000.0       1
2       0  29.0  21000.0       0
3       0  21.0  41700.0       2
4       1  28.0  26100.0       0
...   ...   ...      ...     ...
4995    0  28.0  35700.0       2
4996    0  34.0  52400.0       1
4997    0  20.0  33900.0       2
4998    1  22.0  32700.0       3
4999    1  28.0  40600.0       1

[5000 rows x 4 columns]

Сравним с исходными features:

In [20]:
features

sex   age   salary  family
0       1  41.0  49600.0       1
1       0  46.0  38000.0       1
2       0  29.0  21000.0       0
3       0  21.0  41700.0       2
4       1  28.0  26100.0       0
...   ...   ...      ...     ...
4995    0  28.0  35700.0       2
4996    0  34.0  52400.0       1
4997    0  20.0  33900.0       2
4998    1  22.0  32700.0       3
4999    1  28.0  40600.0       1

[5000 rows x 4 columns]

**Вывод: Данные успешно восстановлены**


## Проверка алгоритма

Создадим модель sklearn_model для проверки метрики R2 и обучим на 2 обучающих матрицах:

 - исходной features
 - кодированной encoded_features

In [21]:
sklearn_model = LinearRegression().fit(features, target)
pred = sklearn_model.predict(features)
r2_score(target, pred)

0.42494550286668

In [22]:
sklearn_model.fit(encoded_features, target)
pred = sklearn_model.predict(encoded_features)
r2_score(target, pred)

0.4249455028666701

**Вывод: R2 по обеим матрицам совпадает.**